apiVersion: batch/v1
kind: Job
metadata:
  name: job2-shared-claim
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: gpu-queue
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        kueue.x-k8s.io/queue-name: gpu-queue
    spec:
      restartPolicy: Never
      resourceClaims:
      - name: gpu
        resourceClaimName: shared-gpu-claim
      containers:
      - name: main
        image: busybox
        command: ["sleep", "300"]
        resources:
          claims:
          - name: gpu 